version: 2.1

orbs:
  snyk: snyk/snyk@2.1.0

jobs:
  build:
    docker:
      - image: cimg/php:8.3.4
    resource_class: small
    steps:
      - checkout
      - run: php --version
      - snyk/install
      - run:
          command: snyk version
          name: Which version of snyk is installed
      - run:
          command: snyk code test
          name: Run code scan
      # Replace this with steps to build a package, or executable
      #- run:
      #    name: Build an artifact
      #    command: touch example.txt
      #- store_artifacts:
      #    path: example.txt
workflows:
  example:
    jobs:
      - build