version: 2.1

orbs:
  snyk: snyk/snyk@2.1.0

jobs:
  build:
    docker:
      - image: cimg/php:8.3.4
    resource_class: small
    steps:
      - checkout
      #- snyk/scan test
      - run: php --version
        name: Install npm dependencies
        command: |
          npm install --save
          php --version
    - snyk/scan:
        fail-on-issues: false
      # Replace this with steps to build a package, or executable
      #- run:
      #    name: Build an artifact
      #    command: touch example.txt
      #- store_artifacts:
      #    path: example.txt
workflows:
  example:
    jobs:
      - build