version: 2.1

jobs:
   build:
    docker:
      - image: cimg/php:8.3.4
    resource_class: small
    steps:
      - checkout
      - run:
          command: php --version
          name: show php version
   deploy:
    docker:
      - image: cimg/php:8.3.4 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
workflows:
  example:
    jobs:
      - build
      - deploy:
          requires:
            - build
